# Generated by Django 4.2.6 on 2023-11-01 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descriptions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('hash', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('image_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cities.base')),
            ],
            bases=('cities.base',),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cities.base')),
            ],
            bases=('cities.base',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cities.base')),
            ],
            bases=('cities.base',),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cities.base')),
            ],
            bases=('cities.base',),
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cities.base')),
                ('website', models.URLField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.PositiveIntegerField()),
                ('city_kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_kitchen', to='cities.city')),
            ],
            bases=('cities.base',),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cities.base')),
                ('price', models.PositiveIntegerField()),
            ],
            bases=('cities.base',),
        ),
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cities.base')),
            ],
            bases=('cities.base',),
        ),
        migrations.AddField(
            model_name='base',
            name='images',
            field=models.ManyToManyField(blank=True, to='cities.image'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cities.base')),
                ('regional_specialties', models.ManyToManyField(to='cities.specialties')),
            ],
            bases=('cities.base',),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_rating', to='cities.event')),
                ('kitchen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_rating', to='cities.kitchen')),
            ],
        ),
        migrations.AddField(
            model_name='kitchen',
            name='menu',
            field=models.ManyToManyField(blank=True, to='cities.menu'),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='kitchen_ratings', to='cities.rating'),
        ),
    ]
