# Generated by Django 4.2.6 on 2023-11-01 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotel',
            name='city_hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_hotel', to='cities.city'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='city_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_event', to='cities.city'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='anonymous_subscribers',
            field=models.ManyToManyField(blank=True, to='users.anonymoususer'),
        ),
        migrations.AddField(
            model_name='city',
            name='city_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_region', to='cities.region'),
        ),
        migrations.AddField(
            model_name='city',
            name='subscribers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attraction',
            name='city_attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_attr', to='cities.city'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('kitchen', 'event')},
        ),
    ]
