# Generated by Django 4.2.6 on 2023-11-01 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('cities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='anonymous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.anonymoususer'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='region',
            name='regional_specialties',
            field=models.ManyToManyField(blank=True, to='cities.specialties'),
        ),
    ]
