# Generated by Django 4.2.6 on 2023-11-01 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_city_anonymous_subscribers_city_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cities.base')),
            ],
            bases=('cities.base',),
        ),
        migrations.RemoveField(
            model_name='region',
            name='regional_specialties',
        ),
        migrations.AddField(
            model_name='region',
            name='regional_specialties',
            field=models.ManyToManyField(to='cities.specialties'),
        ),
    ]
