# Generated by Django 4.2.6 on 2023-11-01 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_specialties_remove_region_regional_specialties_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='id',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='images',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
        migrations.AddField(
            model_name='menu',
            name='base_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cities.base'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='base',
            name='images',
            field=models.ManyToManyField(blank=True, to='cities.image'),
        ),
        migrations.RemoveField(
            model_name='kitchen',
            name='menu',
        ),
        migrations.AddField(
            model_name='kitchen',
            name='menu',
            field=models.ManyToManyField(blank=True, to='cities.menu'),
        ),
    ]
