# Generated by Django 4.2.3 on 2023-11-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notification_anonymous_user_alter_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(max_length=4, verbose_name='Код подтверждения'),
        ),
    ]
